# Generated by Django 3.0.4 on 2020-03-10 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=255)),
                ('name', models.TextField(blank=True, default='', verbose_name='Dialog name')),
                ('finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
