# Generated by Django 3.0.4 on 2020-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.TextField(verbose_name='Dialog name'),
        ),
    ]
