# Generated by Django 3.0.4 on 2020-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_tree', '0002_auto_20200310_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Dialog', 'verbose_name_plural': 'Dialogs'},
        ),
        migrations.AlterField(
            model_name='dialog',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='dialog',
            table='dialogs',
        ),
    ]
