# Generated by Django 3.0.4 on 2020-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_tree', '0003_auto_20200310_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='description',
            field=models.TextField(blank='', default='', verbose_name='Dialog description'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Dialog name'),
        ),
    ]
