# Generated by Django 3.0.4 on 2020-03-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_tree', '0006_auto_20200310_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='next',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dialog_tree.Question', verbose_name='Question'),
            preserve_default=False,
        ),
    ]
