# Generated by Django 3.0.4 on 2020-03-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_tree', '0010_auto_20200310_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='end',
        ),
    ]
