# Generated by Django 3.0.4 on 2020-03-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_tree', '0012_auto_20200312_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='first_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dialogs', to='dialog_tree.Question', verbose_name='First question'),
        ),
    ]
