# Generated by Django 3.0.4 on 2020-03-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_tree', '0013_auto_20200312_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Tree level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dialog_tree.SelfQuestion')),
            ],
            options={
                'verbose_name': 'Self Question',
                'verbose_name_plural': 'Self Questions',
                'db_table': 'self_questions',
            },
        ),
    ]
